# Generated by Django 3.1.2 on 2020-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erporder',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
