# Generated by Django 3.1.2 on 2020-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletorder',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
